name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Deployment Package
        run: |
          zip -r deployment_package.zip .

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
    
      - name: Deploy to AWS Lambda
        env:
          AWS_REGION: eu-north-1
        run: |
          aws lambda update-function-code --function-name elaborate --zip-file fileb://./deployment_package.zip
          aws lambda update-function-configuration --function-name elaborate --handler main.handler
          
      - name: Clean Up
        run: |
          rm deployment_package.zip
          
